id: I545B0328
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T13:02:40+00:00'
last_modified: '2022-06-08T18:16:22.994220+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W16936
  title: གསུང་འབུམ། བློ་བཟང་བཤད་སྒྲུབ་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '6090':
      image_group_id: I4905
      title: ''
      total_pages: 802
      order: 1
      base_file: 6090.txt
    BDCB:
      image_group_id: I4906
      title: ''
      total_pages: 1153
      order: 2
      base_file: BDCB.txt
    5DC5:
      image_group_id: I4907
      title: ''
      total_pages: 990
      order: 3
      base_file: 5DC5.txt
    1D4D:
      image_group_id: I4908
      title: ''
      total_pages: 877
      order: 4
      base_file: 1D4D.txt
    8A3A:
      image_group_id: I4909
      title: ''
      total_pages: 977
      order: 5
      base_file: 8A3A.txt
    FB36:
      image_group_id: I4910
      title: ''
      total_pages: 649
      order: 6
      base_file: FB36.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
